// This file is automatically generated. If your tooling overwrites it,
// keep the same shape but preserve the env checks below.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
// Support both a custom name and the standard ANON key name
const SUPABASE_ANON_KEY = (
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
);

// Fail fast with a clear message (prevents "supabaseUrl is required" mystery)
if (!SUPABASE_URL) {
  throw new Error("Missing VITE_SUPABASE_URL in .env");
}
if (!SUPABASE_ANON_KEY) {
  throw new Error("Missing VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY in .env");
}
// Detect common misconfiguration (non-Supabase keys, e.g. 'sb_publishable_*')
if (SUPABASE_ANON_KEY.startsWith("sb_publishable_")) {
  throw new Error(
    "Invalid API key provided. Use your Supabase project's ANON key (JWT starting with 'ey...') from Project Settings > API."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage,
  },
});
